spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rlafhrdnjs1
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#
#logging:
#  level:
#    org.hibernate.SQL: debug

#    org.hibernate.type: trace # ?? ????? ?? ????? ???